apiVersion: v1
kind: ConfigMap
metadata: 
  name: prom-configmap

data: 
  prometheus.yml: | 
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    
    scrape_configs:
     - job_name: 'Prom-server'
       static_configs:
       - targets: ['localhost:9090']
     - job_name: 'parrot-os'
       static_configs:
       - targets: ['192.168.99.1:9100']


